"""add player_name field

Revision ID: 777ed8523638
Revises: d3316235cd90
Create Date: 2025-01-14 20:28:46.488741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777ed8523638'
down_revision = 'd3316235cd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('player_name')

    # ### end Alembic commands ###
